---
title: "Simulations2"
output: pdf_document
date: "2025-05-13"
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/comparaison-par-paire/R")
library(dplyr)
library(purrr)
library(ggplot2)
library(tidyr)

library(survival)

library(WINS)


library(doParallel)
library(parallel)
library(foreach)
source("fonctions.R")
```

## Scénario 1 : T ~ C

### tau = 0

```{r, HR cst}

n_sim = 2000
n=200


nb_core = parallel::detectCores() - 2
cl = makeCluster(nb_core)
registerDoParallel(cl)
count = 0
start_time = Sys.time()

results = foreach(s = 1:n_sim, .combine = rbind, .packages = c("dplyr", "survival", "parallel", "foreach", "doParallel", "WINS"), .export = c("win.stat")) %dopar% {
  set.seed(s)
  
id=1:(2*n) 
arm=rep(c("T","C"), each=200)
  
U = runif(2*n) 

lambdaT = 0.5
kT = 0.5


Z = ifelse(arm == "T", 1, 0)
beta = 0

prob_T = 0.5
prob_C = 0.5

mean_T = 3
mean_C = 3
sd_T = 2
sd_C = 2

  
Time_1 = round((-log(1 - U)) / (lambdaT * exp(beta * Z)^(1 / kT)),3)
fup_censureT = round(rweibull(n, shape = 1, scale =2),3)

Time_T = pmin(Time_1, fup_censureT)
deltaT=as.numeric(fup_censureT==Time_T)

Y_2_T=as.numeric(gener_binom(prob = prob_T)[,1] )-1
Y_2_C=as.numeric(gener_binom(prob = prob_C)[,1] )-1

Y_3_T= gener_continue(mean = mean_T, sd = sd_T)
Y_3_C= gener_continue(mean = mean_C, sd = sd_C)

stratum=sample(rep(c(1,3,5,8), each = 50))
dataT=data.frame(Y_1 = Time_T[Z==1], Delta_1 = deltaT[Z==1], Y_2 = Y_2_T, Y_3 = Y_3_T, stratum = stratum)
dataC=data.frame(Y_1 = Time_T[Z==0], Delta_1 = deltaT[Z==0], Y_2 = Y_2_C, Y_3 = Y_3_C, stratum = stratum)

 
data1=rbind(dataT,dataC)

summ = summary.data.frame(data1)

min_Y_1 = as.numeric(stringr::str_extract(summ[1,1], "\\d+\\.\\d+"))
min_Y_3 = as.numeric(stringr::str_extract(summ[1,4], "\\d+\\.\\d+"))

nb_0_C=sum(Y_2_C==0)
nb_1_C=sum(Y_2_C==1)

nb_0_T=sum(Y_2_T==0)
nb_1_T=sum(Y_2_T==1)

median_Y_1 = as.numeric(stringr::str_extract( summ[3,1], "\\d+\\.\\d+"))
median_Y_3 = as.numeric(stringr::str_extract( summ[3,4], "\\d+\\.\\d+"))

max_Y_1 =as.numeric(stringr::str_extract(summ[6,1], "\\d+\\.\\d+"))
max_Y_3 =as.numeric(stringr::str_extract(summ[6,4], "\\d+\\.\\d+"))

censure_rateT=sum(dataT$Delta_1==0)/n 
censure_rateC=sum(dataC$Delta_1==0)/n 

data=data.frame(id=id, arm = arm, Y_1= data1[,1],Delta_1=data1[,2], Y_2 = data1[,3], Y_3 = data1[,4], stratum = data1[,5] )

result =
  win.stat(
    data = data,
    ep_type = c("tte", "binary", "continuous"),
    stratum.weight = "equal",
    tau = c(0,0,0),
    arm.name = c("T", "C"),
    alpha = 0.05,
    digit = 3,
    pvalue = "two-sided",
    priority = c(1,2,3),
    summary.print = FALSE
  )

win_edp1=sum(result$summary_ep$Trt_Endpoint1[,2])
loose_edp1=sum(result$summary_ep$Con_Endpoint1[,2])
tie_edp1=4*2500-sum(win_edp1+loose_edp1)

win_edp2=sum(result$summary_ep$Trt_Endpoint2[,2])
loose_edp2=sum(result$summary_ep$Con_Endpoint2[,2])
tie_edp2=tie_edp1-(loose_edp2+win_edp2)

win_edp3 = sum(result$summary_ep$Trt_Endpoint3[,2])
loose_edp3 = sum(result$summary_ep$Con_Endpoint3[,2])
tie_edp3 = tie_edp2-(win_edp3+loose_edp3)


  count = count + 1
  write.table(c(count), file="../output.txt", append = T, col.names = F)
  
  val_GPC = result$Win_statistic$Net_Benefit[1]
  val_WR  = result$Win_statistic$Win_Ratio[1]
  val_WO  = result$Win_statistic$Win_Odds[1]
  
  p_val_GPC = result$p_value[2]
  p_val_WR  = result$p_value[1]
  p_val_WO  = result$p_value[3]
  
  return(unname(c(val_GPC,val_WR,val_WO,win_edp1,loose_edp1,tie_edp1,win_edp2,loose_edp2,tie_edp2,win_edp3,loose_edp3,tie_edp3,min_Y_1, min_Y_3,max_Y_1, max_Y_3,median_Y_1, median_Y_3,nb_0_C,nb_1_C,nb_0_T,nb_1_T, censure_rateC, censure_rateT)))
}
stopCluster(cl)
end_time = Sys.time()
execution_time = end_time - start_time
print(execution_time)

results_df = as.data.frame(results)

min_Y_1=mean(as.numeric(results_df[,13]))
min_Y_3=mean(as.numeric(results_df[,14]))

max_Y_1=mean(as.numeric(results_df[,15]))
max_Y_3=mean(as.numeric(results_df[,16]))

median_Y_1=mean(as.numeric(results_df[,17]))
median_Y_3=mean(as.numeric(results_df[,18]))

nb_O_C = mean(results_df[,19])
nb_1_C = mean(results_df[,20])

nb_O_T = mean(results_df[,21])
nb_1_T = mean(results_df[,22])

censure_rateC= mean(results_df[,23])
censure_rateT= mean(results_df[,24])

df=data.frame(row.names = c("min", "median", "max"), c(min_Y_1, max_Y_1, median_Y_1),c(min_Y_3, max_Y_3, median_Y_3))
colnames(df) = c("Y_1 (tte)", "Y_3 (continue)")

df2 = data.frame(row.name = c("0", "1"), c(nb_O_C,nb_O_T), c(nb_1_C,nb_1_T))
colnames(df2)=c(" ","C", "T")

GPC=as.numeric(results_df[,1])
WR= as.numeric(results_df[,2])
WO= as.numeric(results_df[,3])


quantileGPC_lwr=quantile(GPC, 0.025)
quantileGPC_upr=quantile(GPC, 0.975)
étendue_GPC= round(quantileGPC_upr - quantileGPC_lwr,4)

quantileWR_lwr=quantile(WR, 0.025)
quantileWR_upr=quantile(WR, 0.975)
étendue_WR= round(quantileWR_upr - quantileWR_lwr,4)

quantileWO_lwr=quantile(WO, 0.025)
quantileWO_upr=quantile(WO, 0.975)
étendue_WO= round(quantileWO_upr - quantileWO_lwr,4)


colnames(results_df) = c("val_GPC", "val_WR","val_WO" ,"Win_Edp1","Loose_Edp1","Tie_Edp1","Win_Edp2","Loose_Edp2","Tie_Edp2","Win_Edp3","Loose_Edp3","Tie_Edp3")

Win   = round(c(mean(as.numeric(results_df$Win_Edp1)), mean(as.numeric(results_df$Win_Edp2)), mean(as.numeric(results_df$Win_Edp3)), mean(as.numeric(results_df$Win_Edp1)) + mean(as.numeric(results_df$Win_Edp2)) +mean(as.numeric(results_df$Win_Edp3)) ))

Loose = round(c(mean(as.numeric(results_df$Loose_Edp1)), mean(as.numeric(results_df$Loose_Edp2)),mean(as.numeric(results_df$Loose_Edp3)), mean(as.numeric(results_df$Loose_Edp1))+mean(as.numeric(results_df$Loose_Edp2)) +mean(as.numeric(results_df$Loose_Edp3)) ))

Tie   = round(c(mean(as.numeric(results_df$Tie_Edp1)), mean(as.numeric(results_df$Tie_Edp2)), mean(as.numeric(results_df$Tie_Edp3)), mean(as.numeric(results_df$Tie_Edp3)) ))

df3 = data.frame(
  row.names = c("endpoint1", "endpoint2",  "endpoint3","overall"),
  Win   = Win,
  Loose = Loose,
  Tie   = Tie,
  WR = round(Win/Loose,5),
  WO = round((Win+0.5*Tie)/(Loose+0.5*Tie),5),
  GPC = round((Win-Loose)/(Win+Loose+Tie),5)
)
list(Count = df3, value_tte_cont = df, value_binary = df2, censure_rate_T = censure_rateT, censure_rate_C = censure_rateC)


vlines = data.frame(
    method = c("GPC", "WR", "WO"),
    intercept = c(0, 1, 1),
    linetype_label = "Hypothèse H0")

 values_long = results_df %>%
   select(starts_with("val_")) %>%
   pivot_longer(cols = everything(), names_to = "method", values_to = "value") %>%
   mutate(method = recode(method,
                          "val_GPC" = "GPC",
                          "val_WR"  = "WR",
                          "val_WO"  = "WO"))
 values_long$value = unlist(values_long$value)
 values_long <- values_long %>% filter(!is.infinite(value))


ggplot(values_long, aes(x = value, fill = method)) +
   geom_density(alpha = 0.6, color = "black") +
   geom_vline(data = vlines, aes(xintercept = intercept, linetype = linetype_label),
              color = "black", lwd = 1) +
   theme_minimal() +
   labs(title = "Distribution des statistiques de test",
        x = "Valeur", y = "Densité") +
   scale_linetype_manual(name = "", values = c("Hypothèse H0" = "dashed")) +
   scale_fill_manual(values = c("orange", "purple", "cyan"))+ coord_cartesian(xlim = c(-1, 5))+
  annotate("text", x = 4.5, y = 1.6, label = paste("Étendue GPC : ", étendue_GPC), color = "orange", hjust = 1) +
  annotate("text", x = 4.5, y = 2.35, label = paste("Étendue WR : ", étendue_WR), color = "purple", hjust = 1) +
  annotate("text", x = 4.5, y = 3.1, label = paste("Étendue WO : ", étendue_WO), color = "cyan", hjust = 1)

#ggsave("Rplot_tau0_pb.pdf", device = "pdf", path = "../plots")

```

### tau = 2

```{r, HR cst}

n_sim = 2000
n=200


nb_core = parallel::detectCores() - 2
cl = makeCluster(nb_core)
registerDoParallel(cl)
count = 0
start_time = Sys.time()

results = foreach(s = 1:n_sim, .combine = rbind, .packages = c("dplyr", "survival", "parallel", "foreach", "doParallel", "WINS"), .export = c("win.stat")) %dopar% {
  set.seed(s)
  
id=1:(2*n) 
arm=rep(c("T","C"), each=200)
  
U = runif(2*n) 

lambdaT = 0.5
kT = 0.5


Z = ifelse(arm == "T", 1, 0)
beta = 0

prob_T = 0.5
prob_C = 0.5

mean_T = 3
mean_C = 3
sd_T = 2
sd_C = 2

  
Time_1 = round((-log(1 - U)) / (lambdaT * exp(beta * Z)^(1 / kT)),3)
fup_censureT = round(rweibull(n, shape = 1, scale =2),3)

Time_T = pmin(Time_1, fup_censureT)
deltaT=as.numeric(fup_censureT==Time_T)

Y_2_T=as.numeric(gener_binom(prob = prob_T)[,1] )-1
Y_2_C=as.numeric(gener_binom(prob = prob_C)[,1] )-1

Y_3_T= gener_continue(mean = mean_T, sd = sd_T)
Y_3_C= gener_continue(mean = mean_C, sd = sd_C)

stratum=sample(rep(c(1,3,5,8), each = 50))
dataT=data.frame(Y_1 = Time_T[Z==1], Delta_1 = deltaT[Z==1], Y_2 = Y_2_T, Y_3 = Y_3_T, stratum = stratum)
dataC=data.frame(Y_1 = Time_T[Z==0], Delta_1 = deltaT[Z==0], Y_2 = Y_2_C, Y_3 = Y_3_C, stratum = stratum)

 
data1=rbind(dataT,dataC)

summ = summary.data.frame(data1)

min_Y_1 = as.numeric(stringr::str_extract(summ[1,1], "\\d+\\.\\d+"))
min_Y_3 = as.numeric(stringr::str_extract(summ[1,4], "\\d+\\.\\d+"))

nb_0_C=sum(Y_2_C==0)
nb_1_C=sum(Y_2_C==1)

nb_0_T=sum(Y_2_T==0)
nb_1_T=sum(Y_2_T==1)

median_Y_1 = as.numeric(stringr::str_extract( summ[3,1], "\\d+\\.\\d+"))
median_Y_3 = as.numeric(stringr::str_extract( summ[3,4], "\\d+\\.\\d+"))

max_Y_1 =as.numeric(stringr::str_extract(summ[6,1], "\\d+\\.\\d+"))
max_Y_3 =as.numeric(stringr::str_extract(summ[6,4], "\\d+\\.\\d+"))

censure_rateT=sum(dataT$Delta_1==0)/n 
censure_rateC=sum(dataC$Delta_1==0)/n 

data=data.frame(id=id, arm = arm, Y_1= data1[,1],Delta_1=data1[,2], Y_2 = data1[,3], Y_3 = data1[,4], stratum = data1[,5] )

result =
  win.stat(
    data = data,
    ep_type = c("tte", "binary", "continuous"),
    stratum.weight = "equal",
    tau = c(2,0,2),
    arm.name = c("T", "C"),
    alpha = 0.05,
    digit = 3,
    pvalue = "two-sided",
    priority = c(1,2,3),
    summary.print = FALSE
  )

win_edp1=sum(result$summary_ep$Trt_Endpoint1[,2])
loose_edp1=sum(result$summary_ep$Con_Endpoint1[,2])
tie_edp1=4*2500-sum(win_edp1+loose_edp1)

win_edp2=sum(result$summary_ep$Trt_Endpoint2[,2])
loose_edp2=sum(result$summary_ep$Con_Endpoint2[,2])
tie_edp2=tie_edp1-(loose_edp2+win_edp2)

win_edp3 = sum(result$summary_ep$Trt_Endpoint3[,2])
loose_edp3 = sum(result$summary_ep$Con_Endpoint3[,2])
tie_edp3 = tie_edp2-(win_edp3+loose_edp3)


  count = count + 1
  write.table(c(count), file="../output.txt", append = T, col.names = F)
  
  val_GPC = result$Win_statistic$Net_Benefit[1]
  val_WR  = result$Win_statistic$Win_Ratio[1]
  val_WO  = result$Win_statistic$Win_Odds[1]
  
  p_val_GPC = result$p_value[2]
  p_val_WR  = result$p_value[1]
  p_val_WO  = result$p_value[3]
  
  return(unname(c(val_GPC,val_WR,val_WO,win_edp1,loose_edp1,tie_edp1,win_edp2,loose_edp2,tie_edp2,win_edp3,loose_edp3,tie_edp3,min_Y_1, min_Y_3,max_Y_1, max_Y_3,median_Y_1, median_Y_3,nb_0_C,nb_1_C,nb_0_T,nb_1_T, censure_rateC, censure_rateT)))
}
stopCluster(cl)
end_time = Sys.time()
execution_time = end_time - start_time
print(execution_time)

results_df = as.data.frame(results)

min_Y_1=mean(as.numeric(results_df[,13]))
min_Y_3=mean(as.numeric(results_df[,14]))

max_Y_1=mean(as.numeric(results_df[,15]))
max_Y_3=mean(as.numeric(results_df[,16]))

median_Y_1=mean(as.numeric(results_df[,17]))
median_Y_3=mean(as.numeric(results_df[,18]))

nb_O_C = mean(results_df[,19])
nb_1_C = mean(results_df[,20])

nb_O_T = mean(results_df[,21])
nb_1_T = mean(results_df[,22])

censure_rateC= mean(results_df[,23])
censure_rateT= mean(results_df[,24])

df=data.frame(row.names = c("min", "median", "max"), c(min_Y_1, max_Y_1, median_Y_1),c(min_Y_3, max_Y_3, median_Y_3))
colnames(df) = c("Y_1 (tte)", "Y_3 (continue)")

df2 = data.frame(row.name = c("0", "1"), c(nb_O_C,nb_O_T), c(nb_1_C,nb_1_T))
colnames(df2)=c(" ","C", "T")

GPC=as.numeric(results_df[,1])
WR= as.numeric(results_df[,2])
WO= as.numeric(results_df[,3])


quantileGPC_lwr=quantile(GPC, 0.025)
quantileGPC_upr=quantile(GPC, 0.975)
étendue_GPC= round(quantileGPC_upr - quantileGPC_lwr,4)

quantileWR_lwr=quantile(WR, 0.025)
quantileWR_upr=quantile(WR, 0.975)
étendue_WR= round(quantileWR_upr - quantileWR_lwr,4)

quantileWO_lwr=quantile(WO, 0.025)
quantileWO_upr=quantile(WO, 0.975)
étendue_WO= round(quantileWO_upr - quantileWO_lwr,4)


colnames(results_df) = c("val_GPC", "val_WR","val_WO" ,"Win_Edp1","Loose_Edp1","Tie_Edp1","Win_Edp2","Loose_Edp2","Tie_Edp2","Win_Edp3","Loose_Edp3","Tie_Edp3")

Win   = round(c(mean(as.numeric(results_df$Win_Edp1)), mean(as.numeric(results_df$Win_Edp2)), mean(as.numeric(results_df$Win_Edp3)), mean(as.numeric(results_df$Win_Edp1)) + mean(as.numeric(results_df$Win_Edp2)) +mean(as.numeric(results_df$Win_Edp3)) ))

Loose = round(c(mean(as.numeric(results_df$Loose_Edp1)), mean(as.numeric(results_df$Loose_Edp2)),mean(as.numeric(results_df$Loose_Edp3)), mean(as.numeric(results_df$Loose_Edp1))+mean(as.numeric(results_df$Loose_Edp2)) +mean(as.numeric(results_df$Loose_Edp3)) ))

Tie   = round(c(mean(as.numeric(results_df$Tie_Edp1)), mean(as.numeric(results_df$Tie_Edp2)), mean(as.numeric(results_df$Tie_Edp3)), mean(as.numeric(results_df$Tie_Edp3)) ))

df3 = data.frame(
  row.names = c("endpoint1", "endpoint2",  "endpoint3","overall"),
  Win   = Win,
  Loose = Loose,
  Tie   = Tie,
  WR = round(Win/Loose,5),
  WO = round((Win+0.5*Tie)/(Loose+0.5*Tie),5),
  GPC = round((Win-Loose)/(Win+Loose+Tie),5)
)
list(Count = df3, value_tte_cont = df, value_binary = df2, censure_rate_T = censure_rateT, censure_rate_C = censure_rateC)


vlines = data.frame(
    method = c("GPC", "WR", "WO"),
    intercept = c(0, 1, 1),
    linetype_label = "Hypothèse H0")

 values_long = results_df %>%
   select(starts_with("val_")) %>%
   pivot_longer(cols = everything(), names_to = "method", values_to = "value") %>%
   mutate(method = recode(method,
                          "val_GPC" = "GPC",
                          "val_WR"  = "WR",
                          "val_WO"  = "WO"))
 values_long$value = unlist(values_long$value)
 values_long <- values_long %>% filter(!is.infinite(value))


ggplot(values_long, aes(x = value, fill = method)) +
   geom_density(alpha = 0.6, color = "black") +
   geom_vline(data = vlines, aes(xintercept = intercept, linetype = linetype_label),
              color = "black", lwd = 1) +
   theme_minimal() +
   labs(title = "Distribution des statistiques de test",
        x = "Valeur", y = "Densité") +
   scale_linetype_manual(name = "", values = c("Hypothèse H0" = "dashed")) +
   scale_fill_manual(values = c("orange", "purple", "cyan"))+ coord_cartesian(xlim = c(-1, 5))+
  annotate("text", x = 4.5, y = 1.6, label = paste("Étendue GPC : ", étendue_GPC), color = "orange", hjust = 1) +
  annotate("text", x = 4.5, y = 2.35, label = paste("Étendue WR : ", étendue_WR), color = "purple", hjust = 1) +
  annotate("text", x = 4.5, y = 3.1, label = paste("Étendue WO : ", étendue_WO), color = "cyan", hjust = 1)

```

## Scénario 2 : T>>C

### tau = 0

```{r, HR cst}

n_sim = 2000
n=200


nb_core = parallel::detectCores() - 2
cl = makeCluster(nb_core)
registerDoParallel(cl)
count = 0
start_time = Sys.time()

results = foreach(s = 1:n_sim, .combine = rbind, .packages = c("dplyr", "survival", "parallel", "foreach", "doParallel", "WINS"), .export = c("win.stat")) %dopar% {
  set.seed(s)
  
id=1:(2*n) 
arm=rep(c("T","C"), each=200)
  
U = runif(2*n) 

lambdaT = 0.05
kT = 0.01


Z = ifelse(arm == "T", 1, 0)
beta = 5

prob_T = 0.65
prob_C = 0.3

mean_T = 3
mean_C = 2
sd_T = 2
sd_C = 2

  
Time_1 = round((-log(1 - U)) / (lambdaT * exp(beta * Z)^(1 / kT)),3)
fup_censureT = round(rweibull(n, shape = 1, scale =1),3)

Time_T = pmin(Time_1, fup_censureT)

deltaT=as.numeric(fup_censureT==Time_T)

Y_2_T=as.numeric(gener_binom(prob = prob_T)[,1] )-1
Y_2_C=as.numeric(gener_binom(prob = prob_C)[,1] )-1

Y_3_T= gener_continue(mean = mean_T, sd = sd_T)
Y_3_C= gener_continue(mean = mean_C, sd = sd_C)

stratum=sample(rep(c(1,3,5,8), each = 50))
dataT=data.frame(Y_1 = Time_T[Z==1], Delta_1 = deltaT[Z==1], Y_2 = Y_2_T, Y_3 = Y_3_T, stratum = stratum)
dataC=data.frame(Y_1 = Time_T[Z==0], Delta_1 = deltaT[Z==0], Y_2 = Y_2_C, Y_3 = Y_3_C, stratum = stratum)

 
data1=rbind(dataT,dataC)

summT = summary.data.frame(dataT)

min_Y_1T = as.numeric(stringr::str_extract(summT[1,1], "\\d+\\.\\d+"))
min_Y_3T = as.numeric(stringr::str_extract(summT[1,4], "\\d+\\.\\d+"))

nb_0_C=sum(Y_2_C==0)
nb_1_C=sum(Y_2_C==1)

nb_0_T=sum(Y_2_T==0)
nb_1_T=sum(Y_2_T==1)

median_Y_1T = as.numeric(stringr::str_extract( summT[3,1], "\\d+\\.\\d+"))
median_Y_3T = as.numeric(stringr::str_extract( summT[3,4], "\\d+\\.\\d+"))

max_Y_1T =as.numeric(stringr::str_extract(summT[6,1], "\\d+\\.\\d+"))
max_Y_3T =as.numeric(stringr::str_extract(summT[6,4], "\\d+\\.\\d+"))

summC = summary.data.frame(dataC)

min_Y_1C = as.numeric(stringr::str_extract(summC[1,1], "\\d+\\.\\d+"))
min_Y_3C = as.numeric(stringr::str_extract(summC[1,4], "\\d+\\.\\d+"))


median_Y_1C = as.numeric(stringr::str_extract( summC[3,1], "\\d+\\.\\d+"))
median_Y_3C = as.numeric(stringr::str_extract( summC[3,4], "\\d+\\.\\d+"))

max_Y_1C =as.numeric(stringr::str_extract(summC[6,1], "\\d+\\.\\d+"))
max_Y_3C =as.numeric(stringr::str_extract(summC[6,4], "\\d+\\.\\d+"))

censure_rateT=sum(dataT$Delta_1==0)/n 
censure_rateC=sum(dataC$Delta_1==0)/n 

data=data.frame(id=id, arm = arm, Y_1= data1[,1],Delta_1=data1[,2], Y_2 = data1[,3], Y_3 = data1[,4], stratum = data1[,5] )

result =
  win.stat(
    data = data,
    ep_type = c("tte", "binary", "continuous"),
    stratum.weight = "equal",
    tau = c(0,0,0),
    arm.name = c("T", "C"),
    alpha = 0.05,
    digit = 3,
    pvalue = "two-sided",
    priority = c(1,2,3),
    summary.print = FALSE
  )

win_edp1=sum(result$summary_ep$Trt_Endpoint1[,2])
loose_edp1=sum(result$summary_ep$Con_Endpoint1[,2])
tie_edp1=4*2500-sum(win_edp1+loose_edp1)

win_edp2=sum(result$summary_ep$Trt_Endpoint2[,2])
loose_edp2=sum(result$summary_ep$Con_Endpoint2[,2])
tie_edp2=tie_edp1-(loose_edp2+win_edp2)

win_edp3 = sum(result$summary_ep$Trt_Endpoint3[,2])
loose_edp3 = sum(result$summary_ep$Con_Endpoint3[,2])
tie_edp3 = tie_edp2-(win_edp3+loose_edp3)


  count = count + 1
  write.table(c(count), file="../output.txt", append = T, col.names = F)
  
  val_GPC = result$Win_statistic$Net_Benefit[1]
  val_WR  = result$Win_statistic$Win_Ratio[1]
  val_WO  = result$Win_statistic$Win_Odds[1]
  
  p_val_GPC = result$p_value[2]
  p_val_WR  = result$p_value[1]
  p_val_WO  = result$p_value[3]
  
  return(unname(c(val_GPC,val_WR,val_WO,win_edp1,loose_edp1,tie_edp1,win_edp2,loose_edp2,tie_edp2,win_edp3,loose_edp3,tie_edp3,min_Y_1, min_Y_3,max_Y_1, max_Y_3,median_Y_1, median_Y_3,nb_0_C,nb_1_C,nb_0_T,nb_1_T, censure_rateC, censure_rateT)))
}
stopCluster(cl)
end_time = Sys.time()
execution_time = end_time - start_time
print(execution_time)

results_df = as.data.frame(results)

min_Y_1=mean(as.numeric(results_df[,13]))
min_Y_3=mean(as.numeric(results_df[,14]))

max_Y_1=mean(as.numeric(results_df[,15]))
max_Y_3=mean(as.numeric(results_df[,16]))

median_Y_1=mean(as.numeric(results_df[,17]))
median_Y_3=mean(as.numeric(results_df[,18]))

nb_O_C = mean(results_df[,19])
nb_1_C = mean(results_df[,20])

nb_O_T = mean(results_df[,21])
nb_1_T = mean(results_df[,22])

censure_rateC= mean(results_df[,23])
censure_rateT= mean(results_df[,24])

df=data.frame(row.names = c("min", "median", "max"), c(min_Y_1, max_Y_1, median_Y_1),c(min_Y_3, max_Y_3, median_Y_3))
colnames(df) = c("Y_1 (tte)", "Y_3 (continue)")

df2 = data.frame(row.name = c("0", "1"), c(nb_O_C,nb_O_T), c(nb_1_C,nb_1_T))
colnames(df2)=c(" ","C", "T")

GPC=as.numeric(results_df[,1])
WR= as.numeric(results_df[,2])
WO= as.numeric(results_df[,3])


quantileGPC_lwr=quantile(GPC, 0.025)
quantileGPC_upr=quantile(GPC, 0.975)
étendue_GPC= round(quantileGPC_upr - quantileGPC_lwr,4)

quantileWR_lwr=quantile(WR, 0.025)
quantileWR_upr=quantile(WR, 0.975)
étendue_WR= round(quantileWR_upr - quantileWR_lwr,4)

quantileWO_lwr=quantile(WO, 0.025)
quantileWO_upr=quantile(WO, 0.975)
étendue_WO= round(quantileWO_upr - quantileWO_lwr,4)


colnames(results_df) = c("val_GPC", "val_WR","val_WO" ,"Win_Edp1","Loose_Edp1","Tie_Edp1","Win_Edp2","Loose_Edp2","Tie_Edp2","Win_Edp3","Loose_Edp3","Tie_Edp3")

Win   = round(c(mean(as.numeric(results_df$Win_Edp1)), mean(as.numeric(results_df$Win_Edp2)), mean(as.numeric(results_df$Win_Edp3)), mean(as.numeric(results_df$Win_Edp1)) + mean(as.numeric(results_df$Win_Edp2)) +mean(as.numeric(results_df$Win_Edp3)) ))

Loose = round(c(mean(as.numeric(results_df$Loose_Edp1)), mean(as.numeric(results_df$Loose_Edp2)),mean(as.numeric(results_df$Loose_Edp3)), mean(as.numeric(results_df$Loose_Edp1))+mean(as.numeric(results_df$Loose_Edp2)) +mean(as.numeric(results_df$Loose_Edp3)) ))

Tie   = round(c(mean(as.numeric(results_df$Tie_Edp1)), mean(as.numeric(results_df$Tie_Edp2)), mean(as.numeric(results_df$Tie_Edp3)), mean(as.numeric(results_df$Tie_Edp3)) ))

df3 = data.frame(
  row.names = c("endpoint1", "endpoint2",  "endpoint3","overall"),
  Win   = Win,
  Loose = Loose,
  Tie   = Tie,
  WR = round(Win/Loose,5),
  WO = round((Win+0.5*Tie)/(Loose+0.5*Tie),5),
  GPC = round((Win-Loose)/(Win+Loose+Tie),5)
)
list(Count = df3, value_tte_cont = df, value_binary = df2, censure_rate_T = censure_rateT, censure_rate_C = censure_rateC)


vlines = data.frame(
    method = c("GPC", "WR", "WO"),
    intercept = c(0, 1, 1),
    linetype_label = "Hypothèse H0")

 values_long = results_df %>%
   select(starts_with("val_")) %>%
   pivot_longer(cols = everything(), names_to = "method", values_to = "value") %>%
   mutate(method = recode(method,
                          "val_GPC" = "GPC",
                          "val_WR"  = "WR",
                          "val_WO"  = "WO"))
 values_long$value = unlist(values_long$value)
 values_long <- values_long %>% filter(!is.infinite(value))


ggplot(values_long, aes(x = value, fill = method)) +
   geom_density(alpha = 0.6, color = "black") +
   geom_vline(data = vlines, aes(xintercept = intercept, linetype = linetype_label),
              color = "black", lwd = 1) +
   theme_minimal() +
   labs(title = "Distribution des statistiques de test",
        x = "Valeur", y = "Densité") +
   scale_linetype_manual(name = "", values = c("Hypothèse H0" = "dashed")) +
   scale_fill_manual(values = c("orange", "purple", "cyan"))+ coord_cartesian(xlim = c(-1, 5))+
  annotate("text", x = 4.5, y = 1.6, label = paste("Étendue GPC : ", étendue_GPC), color = "orange", hjust = 1) +
  annotate("text", x = 4.5, y = 2.35, label = paste("Étendue WR : ", étendue_WR), color = "purple", hjust = 1) +
  annotate("text", x = 4.5, y = 3.1, label = paste("Étendue WO : ", étendue_WO), color = "cyan", hjust = 1)


```

### tau = 2

```{r, HR cst}

n_sim = 2000
n=200


nb_core = parallel::detectCores() - 2
cl = makeCluster(nb_core)
registerDoParallel(cl)
count = 0
start_time = Sys.time()

results = foreach(s = 1:n_sim, .combine = rbind, .packages = c("dplyr", "survival", "parallel", "foreach", "doParallel", "WINS"), .export = c("win.stat")) %dopar% {
  set.seed(s)
  
id=1:(2*n) 
arm=rep(c("T","C"), each=200)
  
U = runif(2*n) 

lambdaT = 0.05
kT = 0.01


Z = ifelse(arm == "T", 1, 0)
beta = 5

prob_T = 0.65
prob_C = 0.3

mean_T = 3
mean_C = 2
sd_T = 2
sd_C = 2

  
Time_1 = round((-log(1 - U)) / (lambdaT * exp(beta * Z)^(1 / kT)),3)
fup_censureT = round(rweibull(n, shape = 1, scale =1),3)

Time_T = pmin(Time_1, fup_censureT)
deltaT=as.numeric(fup_censureT==Time_T)

Y_2_T=as.numeric(gener_binom(prob = prob_T)[,1] )-1
Y_2_C=as.numeric(gener_binom(prob = prob_C)[,1] )-1

Y_3_T= gener_continue(mean = mean_T, sd = sd_T)
Y_3_C= gener_continue(mean = mean_C, sd = sd_C)

stratum=sample(rep(c(1,3,5,8), each = 50))
dataT=data.frame(Y_1 = Time_T[Z==1], Delta_1 = deltaT[Z==1], Y_2 = Y_2_T, Y_3 = Y_3_T, stratum = stratum)
dataC=data.frame(Y_1 = Time_T[Z==0], Delta_1 = deltaT[Z==0], Y_2 = Y_2_C, Y_3 = Y_3_C, stratum = stratum)

 
data1=rbind(dataT,dataC)

summ = summary.data.frame(data1)

min_Y_1 = as.numeric(stringr::str_extract(summ[1,1], "\\d+\\.\\d+"))
min_Y_3 = as.numeric(stringr::str_extract(summ[1,4], "\\d+\\.\\d+"))

nb_0_C=sum(Y_2_C==0)
nb_1_C=sum(Y_2_C==1)

nb_0_T=sum(Y_2_T==0)
nb_1_T=sum(Y_2_T==1)

median_Y_1 = as.numeric(stringr::str_extract( summ[3,1], "\\d+\\.\\d+"))
median_Y_3 = as.numeric(stringr::str_extract( summ[3,4], "\\d+\\.\\d+"))

max_Y_1 =as.numeric(stringr::str_extract(summ[6,1], "\\d+\\.\\d+"))
max_Y_3 =as.numeric(stringr::str_extract(summ[6,4], "\\d+\\.\\d+"))

censure_rateT=sum(dataT$Delta_1==0)/n 
censure_rateC=sum(dataC$Delta_1==0)/n 

data=data.frame(id=id, arm = arm, Y_1= data1[,1],Delta_1=data1[,2], Y_2 = data1[,3], Y_3 = data1[,4], stratum = data1[,5] )

result =
  win.stat(
    data = data,
    ep_type = c("tte", "binary", "continuous"),
    stratum.weight = "equal",
    tau = c(2,0,2),
    arm.name = c("T", "C"),
    alpha = 0.05,
    digit = 3,
    pvalue = "two-sided",
    priority = c(1,2,3),
    summary.print = FALSE
  )

win_edp1=sum(result$summary_ep$Trt_Endpoint1[,2])
loose_edp1=sum(result$summary_ep$Con_Endpoint1[,2])
tie_edp1=4*2500-sum(win_edp1+loose_edp1)

win_edp2=sum(result$summary_ep$Trt_Endpoint2[,2])
loose_edp2=sum(result$summary_ep$Con_Endpoint2[,2])
tie_edp2=tie_edp1-(loose_edp2+win_edp2)

win_edp3 = sum(result$summary_ep$Trt_Endpoint3[,2])
loose_edp3 = sum(result$summary_ep$Con_Endpoint3[,2])
tie_edp3 = tie_edp2-(win_edp3+loose_edp3)


  count = count + 1
  write.table(c(count), file="../output.txt", append = T, col.names = F)
  
  val_GPC = result$Win_statistic$Net_Benefit[1]
  val_WR  = result$Win_statistic$Win_Ratio[1]
  val_WO  = result$Win_statistic$Win_Odds[1]
  
  p_val_GPC = result$p_value[2]
  p_val_WR  = result$p_value[1]
  p_val_WO  = result$p_value[3]
  
  return(unname(c(val_GPC,val_WR,val_WO,win_edp1,loose_edp1,tie_edp1,win_edp2,loose_edp2,tie_edp2,win_edp3,loose_edp3,tie_edp3,min_Y_1, min_Y_3,max_Y_1, max_Y_3,median_Y_1, median_Y_3,nb_0_C,nb_1_C,nb_0_T,nb_1_T, censure_rateC, censure_rateT)))
}
stopCluster(cl)
end_time = Sys.time()
execution_time = end_time - start_time
print(execution_time)

results_df = as.data.frame(results)

min_Y_1=mean(as.numeric(results_df[,13]))
min_Y_3=mean(as.numeric(results_df[,14]))

max_Y_1=mean(as.numeric(results_df[,15]))
max_Y_3=mean(as.numeric(results_df[,16]))

median_Y_1=mean(as.numeric(results_df[,17]))
median_Y_3=mean(as.numeric(results_df[,18]))

nb_O_C = mean(results_df[,19])
nb_1_C = mean(results_df[,20])

nb_O_T = mean(results_df[,21])
nb_1_T = mean(results_df[,22])

censure_rateC= mean(results_df[,23])
censure_rateT= mean(results_df[,24])

df=data.frame(row.names = c("min", "median", "max"), c(min_Y_1, max_Y_1, median_Y_1),c(min_Y_3, max_Y_3, median_Y_3))
colnames(df) = c("Y_1 (tte)", "Y_3 (continue)")

df2 = data.frame(row.name = c("0", "1"), c(nb_O_C,nb_O_T), c(nb_1_C,nb_1_T))
colnames(df2)=c(" ","C", "T")

GPC=as.numeric(results_df[,1])
WR= as.numeric(results_df[,2])
WO= as.numeric(results_df[,3])


quantileGPC_lwr=quantile(GPC, 0.025)
quantileGPC_upr=quantile(GPC, 0.975)
étendue_GPC= round(quantileGPC_upr - quantileGPC_lwr,4)

quantileWR_lwr=quantile(WR, 0.025)
quantileWR_upr=quantile(WR, 0.975)
étendue_WR= round(quantileWR_upr - quantileWR_lwr,4)

quantileWO_lwr=quantile(WO, 0.025)
quantileWO_upr=quantile(WO, 0.975)
étendue_WO= round(quantileWO_upr - quantileWO_lwr,4)


colnames(results_df) = c("val_GPC", "val_WR","val_WO" ,"Win_Edp1","Loose_Edp1","Tie_Edp1","Win_Edp2","Loose_Edp2","Tie_Edp2","Win_Edp3","Loose_Edp3","Tie_Edp3")

Win   = round(c(mean(as.numeric(results_df$Win_Edp1)), mean(as.numeric(results_df$Win_Edp2)), mean(as.numeric(results_df$Win_Edp3)), mean(as.numeric(results_df$Win_Edp1)) + mean(as.numeric(results_df$Win_Edp2)) +mean(as.numeric(results_df$Win_Edp3)) ))

Loose = round(c(mean(as.numeric(results_df$Loose_Edp1)), mean(as.numeric(results_df$Loose_Edp2)),mean(as.numeric(results_df$Loose_Edp3)), mean(as.numeric(results_df$Loose_Edp1))+mean(as.numeric(results_df$Loose_Edp2)) +mean(as.numeric(results_df$Loose_Edp3)) ))

Tie   = round(c(mean(as.numeric(results_df$Tie_Edp1)), mean(as.numeric(results_df$Tie_Edp2)), mean(as.numeric(results_df$Tie_Edp3)), mean(as.numeric(results_df$Tie_Edp3)) ))

df3 = data.frame(
  row.names = c("endpoint1", "endpoint2",  "endpoint3","overall"),
  Win   = Win,
  Loose = Loose,
  Tie   = Tie,
  WR = round(Win/Loose,5),
  WO = round((Win+0.5*Tie)/(Loose+0.5*Tie),5),
  GPC = round((Win-Loose)/(Win+Loose+Tie),5)
)
list(Count = df3, value_tte_cont = df, value_binary = df2, censure_rate_T = censure_rateT, censure_rate_C = censure_rateC)


vlines = data.frame(
    method = c("GPC", "WR", "WO"),
    intercept = c(0, 1, 1),
    linetype_label = "Hypothèse H0")

 values_long = results_df %>%
   select(starts_with("val_")) %>%
   pivot_longer(cols = everything(), names_to = "method", values_to = "value") %>%
   mutate(method = recode(method,
                          "val_GPC" = "GPC",
                          "val_WR"  = "WR",
                          "val_WO"  = "WO"))
 values_long$value = unlist(values_long$value)
 values_long <- values_long %>% filter(!is.infinite(value))


ggplot(values_long, aes(x = value, fill = method)) +
   geom_density(alpha = 0.6, color = "black") +
   geom_vline(data = vlines, aes(xintercept = intercept, linetype = linetype_label),
              color = "black", lwd = 1) +
   theme_minimal() +
   labs(title = "Distribution des statistiques de test",
        x = "Valeur", y = "Densité") +
   scale_linetype_manual(name = "", values = c("Hypothèse H0" = "dashed")) +
   scale_fill_manual(values = c("orange", "purple", "cyan"))+ coord_cartesian(xlim = c(-1, 5))+
  annotate("text", x = 4.5, y = 1.6, label = paste("Étendue GPC : ", étendue_GPC), color = "orange", hjust = 1) +
  annotate("text", x = 4.5, y = 2.35, label = paste("Étendue WR : ", étendue_WR), color = "purple", hjust = 1) +
  annotate("text", x = 4.5, y = 3.1, label = paste("Étendue WO : ", étendue_WO), color = "cyan", hjust = 1)


```